services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bot
    restart: on-failure:5
    env_file:
      - .env
    environment:
      TELEGRAM_API_TOKEN: ${TELEGRAM_API_TOKEN}
      URL_GET_SCHEDULE_API: ${URL_GET_SCHEDULE_API}
      ULOGIN: ${ULOGIN}
      UPASSWORD: ${UPASSWORD}
      REDIS_ADDR: ${REDIS_ADDR}
    depends_on:
      - redis

  redis:
    image: redis:8.2-alpine
    container_name: bot-redis
    restart: on-failure:5
    volumes:
      - redisdata:/data
    
volumes:
  redisdata: